debug:  true
server:
  port: 8003
---
ribbon:
  eureka:
    enabled:  false
---
security:
  oauth2:
    client:
      clientId: TnDtPykgih
      clientSecret: fe40xgPd2wwqI3o1tLGD
      accessTokenUri: https://test.appdirect.com/oauth/token
      userAuthorizationUri: https://test.appdirect.com/oauth/authorize
    resource:
      preferTokenInfo:  false
      userInfoUri: https://test.appdirect.com/oauth/openid/userinfo
